version: '2.0'
services:
  converter:
    build: .
    image: cspace-converter
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      CSPACE_CONVERTER_ASYNC_JOBS: 'true'
      CSPACE_CONVERTER_DB_HOST: mongo
      CSPACE_CONVERTER_BASE_URI: https://materials.dev.collectionspace.org/cspace-services
      CSPACE_CONVERTER_DOMAIN: materials.collectionspace.org
      CSPACE_CONVERTER_LOG_LEVEL: debug
      CSPACE_CONVERTER_MODULE: Materials
      CSPACE_CONVERTER_USERNAME: admin@materials.collectionspace.org
      CSPACE_CONVERTER_PASSWORD: Administrator
  mongo:
    image: mongo:3.2
