development:
  clients:
    default:
      database: "<%= ENV.fetch('CSPACE_CONVERTER_DB_NAME') %>_development"
      hosts:
        - <%= "#{ENV.fetch('CSPACE_CONVERTER_DB_HOST', '127.0.0.1')}:27017" %>
production:
  clients:
    default:
      database: "<%= ENV.fetch('CSPACE_CONVERTER_DB_NAME') %>_production"
      hosts:
        - <%= "#{ENV.fetch('CSPACE_CONVERTER_DB_HOST', '127.0.0.1')}:27017" %>
test:
  clients:
    default:
      database: "<%= ENV.fetch('CSPACE_CONVERTER_DB_NAME') %>_test"
      hosts:
        - <%= "#{ENV.fetch('CSPACE_CONVERTER_DB_HOST', '127.0.0.1')}:27017" %>
      options:
        read:
          mode: :primary
        max_pool_size: 1
